sudo: required
language: php
php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql

before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/test_db.sh
  - wget https://raw.githubusercontent.com/jpina/oci8/master/bin/install_oci8_ext.sh
  - wget https://raw.githubusercontent.com/jpina/oci8/master/bin/instantclient-basic-linux.x64-12.1.0.2.0.zip
  - wget https://raw.githubusercontent.com/jpina/oci8/master/bin/instantclient-sdk-linux.x64-12.1.0.2.0.zip
  - bash accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash test_db.sh
  - bash install_oci8_ext.sh
  - echo "extension = oci8.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo /etc/init.d/apache2 restart
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root test < tests/db.sql
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester tests -s

jobs:
  include:
    -   name: Nette Code Checker
        install:
          - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
        script:
          - php temp/code-checker/code-checker --strict-types


    -   name: Nette Coding Standard
        install:
          - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
        script:
          - php temp/coding-standard/ecs check src examples --config temp/coding-standard/coding-standard-php71.yml


    - stage: Code Coverage
      script:
        - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
      after_script:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        - php coveralls.phar --verbose --config tests/.coveralls.yml
