sudo: required
language: php
php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql

before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - wget https://raw.githubusercontent.com/accgit/docker/master/docker-oracle/oracle/oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb
  - wget https://raw.githubusercontent.com/accgit/docker/master/docker-oracle/oracle/oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
  - bash accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash tests/db.add.tabe.sh
  - sudo dpkg -i oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb
  - sudo dpkg -i oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
  - echo 'instantclient,/usr/lib/oracle/12.2/client64/lib' | pecl install oci8
  - echo "extension = oci8.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - export LD_LIBRARY_PATH=/usr/lib/oracle/12.2/client64/lib/
  - export ORACLE_HOME=/usr/lib/oracle/12.2/client64/lib/
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root test < tests/db.sql
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester -c tests/php.oracle.ini tests -s

jobs:
  include:
    -   name: Nette Code Checker
        install:
          - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
        script:
          - php temp/code-checker/code-checker --strict-types


    -   name: Nette Coding Standard
        install:
          - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
        script:
          - php temp/coding-standard/ecs check src examples --config temp/coding-standard/coding-standard-php71.yml


    - stage: Code Coverage
      script:
        - vendor/bin/tester -c tests/php.oracle.ini -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
      after_script:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        - php coveralls.phar --verbose --config tests/.coveralls.yml
