sudo: required
services:
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root test < tests/db.sql
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

jobs:
  include:
    -   name: Nette Code Checker
        install:
          - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
        script:
          - php temp/code-checker/code-checker --strict-types
        language: php
        php:
          - 7.1


    -   name: Nette Coding Standard
        install:
          - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
        script:
          - php temp/coding-standard/ecs check src examples --config temp/coding-standard/coding-standard-php71.yml
        language: php
        php:
          - 7.1


    -   name: PHP 7.1
        install:
          - travis_retry composer require nette/tester --dev
        script:
          - vendor/bin/tester -c tests/php.oracle.ini tests -s
        before_script:
          - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
          - wget https://raw.githubusercontent.com/accgit/docker/master/docker-oracle/oracle/oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb
          - wget https://raw.githubusercontent.com/accgit/docker/master/docker-oracle/oracle/oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
          - bash accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
          - bash tests/db.add.tabe.sh
          - sudo dpkg -i oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb
          - sudo dpkg -i oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
          - echo 'instantclient,/usr/lib/oracle/12.2/client64/lib' | pecl install oci8
        language: php
        php:
          - 7.1


    -   name: PHP 7.2
        install:
          - travis_retry composer require nette/tester --dev
        script:
          - vendor/bin/tester -c tests/php.oracle.ini tests -s
        before_script:
          - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
          - wget https://raw.githubusercontent.com/accgit/docker/master/docker-oracle/oracle/oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb
          - wget https://raw.githubusercontent.com/accgit/docker/master/docker-oracle/oracle/oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
          - bash accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
          - bash tests/db.add.tabe.sh
          - sudo dpkg -i oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb
          - sudo dpkg -i oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
          - echo 'instantclient,/usr/lib/oracle/12.2/client64/lib' | pecl install oci8
        language: php
        php:
          - 7.2


    -   name: PHP 7.3
        install:
          - travis_retry composer require nette/tester --dev
        script:
          - vendor/bin/tester -c tests/php.oracle.ini tests -s
        before_script:
          - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
          - wget https://raw.githubusercontent.com/accgit/docker/master/docker-oracle/oracle/oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb
          - wget https://raw.githubusercontent.com/accgit/docker/master/docker-oracle/oracle/oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
          - bash accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
          - bash tests/db.add.tabe.sh
          - sudo dpkg -i oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb
          - sudo dpkg -i oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
          - echo 'instantclient,/usr/lib/oracle/12.2/client64/lib' | pecl install oci8
        language: php
        php:
          - 7.3
