export ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe;
export ORACLE_SID=XE;
$ORACLE_HOME/bin/sqlplus -S travis/travis <<SQL
whenever sqlerror exit 2;
CREATE SEQUENCE TEST_SEQ;
CREATE TABLE TEST (SAMPLE_ID INTEGER NOT NULL PRIMARY KEY, SAMPLE_STRING VARCHAR2(255) NOT NULL);
INSERT INTO TEST(SAMPLE_ID, SAMPLE_STRING) VALUES (1,'Hello');
SQL