DROP TABLE IF EXISTS test;
CREATE TABLE test (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  sample VARCHAR(255) NOT NULL
)
  ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

INSERT INTO test (sample) VALUES ('Hello');
